// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.25.1";

// src/lib/mcp/tools/get-profile.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.25.1";

// src/lib/mcp/content.ts
var profile = {
  name: "Aman Chaurasia",
  headline: "AI / Software Development Engineer",
  summary: "Creative developer and engineer working across full-stack development, generative AI, machine learning and AI workflow automation. Driven by curiosity and always exploring new technologies.",
  focusAreas: [
    "Full Stack Development",
    "Generative AI (LLMs, chatbots, content tooling)",
    "Machine Learning & Data Science",
    "AI workflow automation and MLOps"
  ],
  contact: "Use the contact section of the portfolio site to get in touch."
};
var techStack = [
  {
    category: "Languages & Libraries",
    items: ["Python", "Pandas", "Scikit-learn", "Flask", "SQL", "Bash", "HTML", "CSS", "JavaScript", "Node.js"]
  },
  {
    category: "Machine Learning",
    items: ["Supervised Learning", "Unsupervised Learning", "PyTorch", "TensorFlow", "AWS SageMaker"]
  },
  {
    category: "Generative AI & NLP",
    items: ["LangChain", "Hugging Face", "Prompt Engineering", "OpenAI"]
  },
  {
    category: "Data Science",
    items: ["EDA", "Feature Engineering", "Data Visualization", "Statistics"]
  },
  {
    category: "MLOps & Pipelines",
    items: ["MLflow", "Apache Airflow", "DVC", "CI/CD", "Docker", "Kubernetes"]
  },
  {
    category: "Tools & Platforms",
    items: ["Git", "AWS", "Grafana", "Tableau", "Excel", "Dagshub", "Linux"]
  }
];
var experience = [
  {
    company: "Provana",
    location: "Noida, India",
    role: "Software Engineer \u2013 AI/ML",
    period: "August 2026 \u2013 Present",
    highlights: [
      "Architected and shipped a production real-time AI Nudge Generation Service on Azure Function Apps, running Gemini and Gemma on Vertex AI via Google ADK with sub-second end-to-end latency.",
      "Designed stateful multi-turn conversation handling with Google ADK session management backed by PostgreSQL.",
      "Built dual-path nudge delivery with Gemini-generated responses, guaranteed-SLA template fallbacks, and chunk-level streaming through Azure Web PubSub.",
      "Engineered a five-function post-call AI analytics suite on Azure Service Bus and Vertex AI, with Azure Blob Storage persistence and Langfuse plus OpenTelemetry observability."
    ]
  },
  {
    company: "Krutanic",
    role: "Data Science Intern",
    period: "2025",
    highlights: [
      "Applied data analysis and machine learning techniques to solve business problems."
    ]
  }
];

// src/lib/mcp/tools/get-profile.ts
var get_profile_default = defineTool({
  name: "get_profile",
  title: "Get profile",
  description: "Get Aman Chaurasia's professional profile summary, headline and focus areas.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(profile, null, 2) }],
    structuredContent: { profile }
  })
});

// src/lib/mcp/tools/list-tech-stack.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.25.1";
import { z } from "npm:zod@^3.25.76";
var list_tech_stack_default = defineTool2({
  name: "list_tech_stack",
  title: "List tech stack",
  description: "List Aman's technical skills, optionally filtered by a category name or keyword.",
  inputSchema: {
    query: z.string().optional().describe("Optional keyword to filter categories or skills.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ query }) => {
    const q = query?.trim().toLowerCase();
    const results = !q ? techStack : techStack.map((c) => ({
      category: c.category,
      items: c.category.toLowerCase().includes(q) ? c.items : c.items.filter((i) => i.toLowerCase().includes(q))
    })).filter((c) => c.items.length > 0);
    return {
      content: [{ type: "text", text: JSON.stringify(results, null, 2) }],
      structuredContent: { categories: results }
    };
  }
});

// src/lib/mcp/tools/list-experience.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.25.1";
var list_experience_default = defineTool3({
  name: "list_experience",
  title: "List work experience",
  description: "List Aman's work experience with roles, dates and key achievements.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(experience, null, 2) }],
    structuredContent: { experience }
  })
});

// src/lib/mcp/index.ts
var projectRef = "lgdefgukyglinpgonooq";
var mcp_default = defineMcp({
  name: "aman18-07chaurasia",
  title: "aman18-07chaurasia",
  version: "0.1.0",
  instructions: "Tools for Aman Chaurasia's portfolio. Use `get_profile` for an overview, `list_tech_stack` for skills, and `list_experience` for work history.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [get_profile_default, list_tech_stack_default, list_experience_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.25.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
